#!/bin/sh
#
# PROVIDE: shaperoute
# REQUIRE: DAEMON mysql
# KEYWORD: shutdown

. /etc/rc.subr

name="shaperoute"
rcvar=`set_rcvar`

cd /usr/shaperoute
required_files="/usr/shaperoute/main.py"
command="/usr/shaperoute/main.py"
command_args="127.0.0.1:9002 > /var/log/${name}.log 2>&1 &"
command_interpreter="/usr/local/bin/python"

load_rc_config $name
run_rc_command "$1"
